#!/bin/sh -eu

stdbuf -oL journalctl -fu aprs-log -n 0 -o json |
	jq --unbuffered -rf "`dirname $0`/aprs-ahma.jq" |
	while read -r line; do
		echo "copy ahma from stdin (format csv);
$line
\\."
	done | psql hacklabjkl_sensor
