#!/bin/sh -eu

if test $# -ne 1; then
    echo Usage: $0 BALANCE_CONFIG_JSON >&2
    echo >&2
    echo Reads standard input and outputs Icinga perfdata line >&2
    exit 3
fi

own="`dirname $0`"
tmp=`mktemp`

cat "$own/split_lines.jq" >>$tmp
cat "$own/icinga.jq" >>$tmp 

# Produce limits and put data in
cat "$own/balance_check.jq" >>$tmp

jq -Rrsf $tmp --slurpfile conf "$1" | {
    read ret
    cat
    rm $tmp
    exit $ret
}
