#!/bin/sh -eu

if test $# -ne 1; then
    echo Usage: $0 BALANCE_CONFIG_JSON >&2
    echo >&2
    echo Reads standard input and outputs Icinga perfdata line >&2
    exit 3
fi

own="`dirname $0`"
tmp=`mktemp`

cat "$own/split_lines.jq" >>$tmp
cat "$own/icinga.jq" >>$tmp 

# Produce limits and put data in
cat "$own/balance_fill.jq" >>$tmp
echo '| fill_icinga_state | ' >>$tmp

# Check limits

# Add msg and exit values based on checked limits
cat "$own/msg_and_exit.jq" >>$tmp
echo '| to_perfdata' >>$tmp

# Produce Icinga perfdata lines

#echo $tmp
#exit 0

jq -Rrsf $tmp --slurpfile conf "$1" | {
    read ret
    cat
    rm $tmp
    exit $ret
}
