#!/bin/sh -eu

stats () {
    sox -t "$1" - -n stat 2>&1 |
	jq -sRrf "`dirname $0`/stream_monitor.jq" | {
	read ret
	head -n 1
	exit $ret
    }
}

curl_head () {
    curl "$1" | head -c 65536
}

case "$1" in
    opus)
	curl_head "$2" | opusdec --force-wav - - | stats wav
	;;
    mp3)
	curl_head "$2" | stats mp3
	;;
    *)
	echo "Invalid command" >&2
	exit 3
esac
