#!/bin/sh -eu

stats () {
    own="`dirname $0`"
    sox -t "$1" - -n stat 2>&1 |
	jq -sRrf "$own/stream_monitor.jq" -L "$own" | {
	read ret
	head -n 1
	exit $ret
    }
}

curl_head () {
    curl -s "$1" | head -c 65536
}

case "$1" in
    opus)
	curl_head "$2" | opusdec --quiet --force-wav - - 2>/dev/null | stats wav
	;;
    mp3)
	curl_head "$2" | stats mp3
	;;
    *)
	echo "Invalid command" >&2
	exit 3
esac
